baseURL = 'https://canton-tabletop.org/'
languageCode = 'en-us'
title = 'Canton Tabletop Gamers'
theme = 'pehtheme-hugo'

paginate = '6' # <- Set the desired number of posts per page
summaryLength = '20' # <- 20 words are approximately 160 characters
# googleAnalytics = 'G-MEASUREMENT_ID' # <- Your GA-4
# disqusShortname = 'your-disqus-shortname' # <- Get form here : https://disqus.com

[params]
    # Meta description, not exceeding 160 characters, used for the meta description within the HTML head
    description = 'Canton Tabletop Gamers: Board gaming group in Canton, Ohio, USA'
    mainSections = 'posts'
    mainCategory = 'boardgames'
    comments = false

[author]
    name = 'Canton Tabletop Gamers'
    bio = 'Tabletop board gaming in Canton Ohio'
    #avatar = '/images/nasa-astronaut-unsplash.jpg'
    #twitter = 'https://twitter.com/insertapps'

[menu] # Menu management
    [[menu.main]]
        name = 'Home'
        pageRef = '/'
        weight = 10
    [[menu.main]]
        name = 'About'
        pageRef = '/about'
        weight = 15
    [[menu.main]]
        name = 'Tags'
        pageRef = '/tags'
        weight = 20

[module]
  [module.hugoVersion]
    extended = false
    min = "0.116.0"
  [module.mounts] # Directing the static folder to assets.
    source = 'assets'
    target = 'static'
